spring.datasource.url=jdbc:postgresql://localhost:5432/MovieApp
spring.datasource.username=postgres
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
tmdb.api.key=99065c82c437d940287b4ee6ca1e34ed